### ISSUE TITLE
Merge changes back to origin?

### ISSUE THREAD

**Issue by bormm** [rossknudsen/OpenMCDF#2]
This project is a old fork of the original OpenMcdf source hosted on sourceforge. I would recommend using and improving the original now, after it also moved to github a while ago: (https://github.com/ironfede/openmcdf).

**Comment by rossknudsen** [comment]
Hi @bormm,

Thanks for pointing this out to me.  I've just checked that any changes I made have been included in ironfede's repo.  I'll update the Readme here to point to that repository for a period of time.  Then I'll delete this one.
